# Generated by Django 3.2.5 on 2022-06-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTPUFoodie_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodieDatabase1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_field', models.CharField(blank=True, db_column='No.', max_length=7, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=33, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=18, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=5, null=True)),
            ],
            options={
                'db_table': 'foodie_database_1_',
                'managed': False,
            },
        ),
    ]
