# Generated by Django 3.2.5 on 2022-06-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NTPUFoodie_bot', '0002_foodiedatabase1'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodieDatabase',
            fields=[
                ('column1', models.IntegerField(db_column='Column1', primary_key=True, serialize=False)),
                ('restaurant', models.CharField(blank=True, db_column='Restaurant', max_length=33, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=18, null=True)),
                ('class_field', models.CharField(blank=True, db_column='Class', max_length=3, null=True)),
            ],
            options={
                'db_table': 'foodie_database',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FoodieDatabase1',
        ),
    ]
